/*******************************************************************************
 * Copyright (c) 2013 Jeremy.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Public License v3.0
 * which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/gpl.html
 * 
 * If you'd like to obtain a another license to this code, you may contact Jeremy to discuss alternative redistribution options.
 * 
 * Contributors:
 *     Jeremy - initial API and implementation
 ******************************************************************************/

package io.github.jevaengine.mapeditor;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeremy
 */
public class Configuration extends javax.swing.JDialog
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private boolean m_isValid = false;
	
	/**
	 * Creates new form NewMap
	 */
	public Configuration(java.awt.Frame parent, boolean modal)
	{
		super(parent, modal);
		initComponents();
	}

	public boolean isLastQueryValid()
	{
		return m_isValid;
	}
	
	public String getBaseDirectory()
	{
		return txtBaseDirectory.getText();
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	//@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnCancel = new javax.swing.JButton();
        btnOkay = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtBaseDirectory = new javax.swing.JTextField();
        btnBrowseBase = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editor Configuration");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelActionPerformed(evt);
            }
        });

        btnOkay.setText("Okay");
        btnOkay.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOkayActionPerformed(evt);
            }
        });

        jLabel3.setText("Base Directory:");

        txtBaseDirectory.setEditable(false);
        txtBaseDirectory.setName("txtBaseDirectory"); // NOI18N

        btnBrowseBase.setText("...");
        btnBrowseBase.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnBrowseBaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBaseDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnBrowseBase, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOkay)
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBaseDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowseBase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOkay))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	@Override
	public void setVisible(boolean isVisible)
	{
		if(isVisible)
			m_isValid = false;
		
		super.setVisible(isVisible);
	}
	
    private void btnBrowseBaseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnBrowseBaseActionPerformed
    {//GEN-HEADEREND:event_btnBrowseBaseActionPerformed
        JFileChooser chooser = new JFileChooser();
		chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		
		if(chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
		{
			txtBaseDirectory.setText(chooser.getSelectedFile().getAbsolutePath());
		}
    }//GEN-LAST:event_btnBrowseBaseActionPerformed

    private void btnOkayActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOkayActionPerformed
    {//GEN-HEADEREND:event_btnOkayActionPerformed
        if(txtBaseDirectory.getText().length() != 0)
		{
			m_isValid = true;
			this.setVisible(false);
		}else
			JOptionPane.showMessageDialog(this, "All fields must be filled before you can continue.");
    }//GEN-LAST:event_btnOkayActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelActionPerformed
    {//GEN-HEADEREND:event_btnCancelActionPerformed
        m_isValid = false;
		this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseBase;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOkay;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtBaseDirectory;
    // End of variables declaration//GEN-END:variables
}
